plane-ce:
  extraEnv:
    - name: "EMAIL_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: "plane-smtp-secrets"
          key: "smtp-password"
  smtp:
    enabled: true
    host: "in-v3.mailjet.com"
    user: "e249b8ca4c279516b7a38439bad75854"
    from: "Plane HFSWMS <plane@mail.hfswms.org>"
    port: 587
    use_tls: 1
  apollo:
    overwrite_fe_url: "https://plane.hfswms.org"
  planeVersion: v1.2.1
  license:
    licenseDomain: "plane.hfswms.org" 
  ingress:
    enabled: true
    ingressClass: "traefik"
    appHost: "plane.hfswms.org"
    ingress_annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: "plane.hfswms.org"
      paths:
      - path: /
        pathType: ImplementationSpecific
  ssl:
    tls_secret_name: "plane-hfswms-org-tls"
  env:
    storageClass: "longhorn"
