apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-dlp-webui-deployment
  labels:
    app: yt-dlp-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-dlp-webui
  template:
    metadata:
      labels:
        app: yt-dlp-webui
    spec:
      containers:
      - name: yt-dlp-webui
        image: marcobaobao/yt-dlp-webui:latest
        ports:
        - containerPort: 3033
        volumeMounts:
        - name: downloads-volume
          mountPath: /downloads
        # Optional: Mount a config file if needed
        # - name: config-volume
        #   mountPath: /config
      volumes:
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: yt-dlp-pvc # Replace with your PVC name
        # Optional: Define config volume if needed
        # - name: config-volume
        #   configMap:
        #     name: yt-dlp-config # Replace with your ConfigMap name
