apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin-web-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: "notes.hfswms.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: joplin-service
            port:
              number: 80
  tls:
  - secretName: notes-hfswms-org-tls
