apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden # Target namespace for the deployment
    server: https://kubernetes.default.svc
  project: default
  sources:
    # Source 1: The remote Helm Chart
    - repoURL: https://guerzon.github.io/vaultwarden/
      chart: vaultwarden
      targetRevision: 0.18.0
      helm:
        valueFiles:
          - $values/applications/vaultwarden/values.yaml
    # Source 2: Your Git Repository containing the values.yaml
    - repoURL: https://github.com/Gsmith2518/hfswms-argo
      targetRevision: main
      ref: values  # This 'ref' matches the '$values' prefix above
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # Automatically sync any drift from Git
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane-app
  namespace: argocd
spec:
  destination:
    namespace: plane-ce # Target namespace for the deployment
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Gsmith2518/hfswms-argo
    targetRevision: HEAD
    path: 'applications/plane'
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # Automatically sync any drift from Git
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  destination:
    namespace: wireguard
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Gsmith2518/hfswms-argo
    targetRevision: HEAD
    path: 'applications/wireguard'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
