ingress:
  enabled: true
  class: "traefik"
  hostname: passwords.hfswms.org
  additionalAnnotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
  
  # Reference the pre-existing wildcard secret
  tls:
    - secretName: passwords-hfswms-org-tls
      hosts:
        - passwords.hfswms.org
image:
  tag: 1.34.3-alpine # Use an immutable tag
# Enable persistence
persistence:
  config:
    enabled: true
    type: pvc
    size: 5Gi
domain: "https://passwords.hfswms.org"
