ingress:
  enabled: true
  class: "traefik"
  hostname: passwords.hfswms.org
  tlsSecret: wildcard-hfswms-org-tls
image:
  tag: 1.34.3-alpine # Use an immutable tag
# Enable persistence
persistence:
  config:
    enabled: true
    type: pvc
    size: 5Gi
domain: "https://passwords.hfswms.org"
