argo-cd:
  global:
    domain: argocd.hfswms.org
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hostname: argocd.hfswms.org
      path: /
      tls:
        secretName: argocd-server-tls

    service:
      servicePortHttp: 443
